{
    "composition.field.add": "Legg til et felt",
    "composition.field.deleteConfirmation": "Er du sikker på at du vil slette dette felt?",
    "composition.field.core.campaignmonitor": "Nyhetsbrev påmelding",
    
    
    "composition.field.core.date": "Datovelger",
    
    "composition.field.core.email": "E-postadresse",
    "composition.field.core.heading": "Overskrift",
    "composition.field.core.image": "Bilde",
    "composition.field.core.link": "Lenke",
    "composition.field.core.telephone": "Telefon",
    "composition.field.core.mailchimp": "Nyhetsbrevpåmelding",
    "composition.field.core.memberinfo": "Medlemsinformasjon",
    "composition.field.core.number": "Heltall",

    "composition.field.core.checkbox": "Velg / bekreft",
    "composition.field.core.dropdown": "Velg én (nedtrekksliste)",
    "composition.field.core.radiobuttongroup": "Velg én (knapper)",
    "composition.field.core.selectbox": "Velg flere (liste)",
    "composition.field.core.checkboxgroup": "Velg flere (knapper)",
    
    "composition.field.core.consent": "Innleveringsbekreftelse",

    "composition.field.core.recaptcha": "Spambeskyttelse (reCAPTCHA)",    
    "composition.field.core.submitbutton": "Lagreknapp",
    "composition.field.core.textarea": "Tekstfelt (en linje)",
    "composition.field.core.textbox": "Tekstboks (flere linjer)",
    "composition.field.core.textParagraph": "Tekst / informasjon",
    "composition.field.core.upload": "Filopplasting",
    "composition.field.core.url": "Webadresse",
    "composition.header": "Design/layout",
    "composition.pages.add": "Legg til en side",
    "composition.pages.empty": "Klikk her for å legge til en side",
    "composition.pages.header": "Side nr. ",
    "composition.pick.field.header": "Legg til et felt",
    "composition.pick.field.text": "Velg hva slags felt som skal legges til",
    "composition.pick.row.header": "Legg til en rad",  
    "composition.pick.row.text": "Velg hva slags rad som skal legges til",  
    "composition.row.add": "Legg til en rad",
    "composition.row.deleteConfirmation": "Er du sikker på, at du vil slette denne raden?",
    "composition.row.one-column": "Enkelkolonne",
    "composition.row.two-column": "To kolonner",
    "composition.row.two-column-wide-left": "To kolonner (bred venstrekolonne)",
    "composition.row.two-column-wide-right": "To kolonner (bred høyrekolonne)",
    "composition.row.three-column": "Tre kolonner",
    "composition.rows.empty": "Klikk her for å legge til en rad",
    "composition.text": "Du lager et skjema ved å velge relevante felter. Ved å trykke på «+ Legg til et felt» får du meny over ulike felt-alternativer. Du kan legge til og trekke fra felter senere. Du kan velge å sette opp feltene i en eller 2 rader.",

    "validation.add": "Legg til validering",
    "validation.condition.core.fieldisempty": "Feltet er tomt",
    "validation.condition.core.fieldisnotempty": "Feltet er ikke tomt",
    "validation.condition.core.fieldvalueis": "Verdien er",
    "validation.condition.core.fieldvalueisnot": "Verdien er ikke",
    "validation.condition.core.fieldvaluesdonotmatch": "Verdien matcher ikke et andet felt",
    "validation.condition.core.fieldvaluesmatch": "Verdien matcher et andet felt",
    "validation.errorMessage.header": "...skal denne feilmelding vises:",
    "validation.header": "Validering",
    "validation.pick.field": "Velg et felt:",
    "validation.pick.condition": "Velg en betingelse:",
    "validation.rules.fieldHeader": "Felt",
    "validation.rules.conditionHeader": "Betingelse",
    "validation.rules.add": "Legg til en regel",
    "validation.rules.add.header": "Legg til en regel",
    "validation.rules.add.text": "En regel består av et felt og en betingelse. Hvis feltets verdi oppfyller betingelsen, er reglen oppfylt.",
    "validation.rules.header": "Hvis disse regler er oppfylt...",
    "validation.text": "Her kan du sette valideringer opp, der går på tvers av de enkelte felt i skjemaet - f.eks. \"skjemaet er ugyldig hvis felt A er tomt og felt B ikke er tomt\".",
    "validation.text.noFields": "Du må legg til felter til skjemaet, før du kan sette opp validering.",

    "actions.header": "Handlinger",
    "actions.text": "Her kan du opprette handlinger, som viser eller skjuler felter baseret på andre felters verdi - f.eks. \"vis kun felt A hvis felt B ikke er tomt\".",
    "action.task.header": "...skal denne handling utføres:",
    "action.add": "Legg til en handling",
    "action.text.noFields": "Du må legg tile felter i skjemaet, før du kan opprette handlinger.",

    "email.submittedValues.helpText": "I teksten kan du flette inn data fra feltene som bruker har fylt ut i skjemaet. Skriv inn det unike feltnavnet med klammeparrantes rund. F.eks. [name]: Navnet som bruker har skrevet inn i navnefeltet i sitt skjema flettes da inn i teksten på din e-post. Du kan også inkludere lenker til web adresser, e-post etc.",

    "emails.header": "E-postbekreftelse",
    "emailConfirmation.header": "E-post bekreftelse/takk til bruker",
    "emailConfirmation.text": "Her setter du opp e-post som kan sendes automatisk til bruker når skjemaet er fyll ut.",
    "emailConfirmation.recipientsField": "E-postadresse felt",
    "emailConfirmation.subject": "Emnetekst",
    "emailConfirmation.body": "Innhold",
    "emailConfirmation.sender": "Avsenders e-postadresse",

    "emailNotification.attachments": "Legg ved opplastede filer til mailen",
    "emailNotification.attachments.helpText": "Hvis du velger dette, må du overveie faren for virus og filstørrelser.",
    "emailNotification.header": "E-postvarsling",
    "emailNotification.text": "Hvis du vil ha e-post varsling når bruker sender inn skjema må du legge inn e-postadresse, emnetekst og avsender under.",
    "emailNotification.recipients": "Mottakers adresse",
    "emailNotification.subject": "Emnetekst",
    "emailNotification.sender": "Avsenders e-postadresse",
  
    "receipt.header" : "Takkeside",
    "receipt.page": "Velg side",
    "receipt.page.header": "Velg mellom 2 alternative måter å presentere «Takkeside».<br/><br/>1. Takk & bekreftelse på separat nettside",
    "receipt.page.text": "Takkesiden opprettes først i menyen som «artikkel» og redigeres derfra som en vanlig unik Umbraco-side. Koble Takkesiden til din skjema-/kampanjesiden her:",
    "receipt.page.select": "Velg...",
    "receipt.message.header": "2. Takk & bekreftelse direkte på skjema-/kampanjesiden",
    "receipt.message.text": "Hele skjemaet forsvinner fra kampanjesiden og erstattes av din takke-tekst.",
    "receipt.message.heading": "Overskrift",
    "receipt.message.body": "Tekst",

    "limitations.header": "Begrensninger",

    "data.header": "Rapport",
    "data.text": "Her kan du se data som brukerne har sendt inn.",
    "data.visibleFields.header": "Velg felter som skal vises", 
    "data.visibleFields.text": "Velg feltene som skal vises i tabellen. Hvis du velger å skjule et eller flere felt, kan du klikke på en rad i tabellen for at se alle feltene.", 
    "data.sortSubmittedDate": "Dato",
    "data.pagePrevious": "Forrige",
    "data.pageNext": "Neste",
    "data.exportAllToCsv": "Eksporter til CSV",
    "data.deleteSelected": "Slett valgte",
    "data.loadingData": "Henter skjemadata...",
    "data.noData": "Ingen skjemadata funnet",
    "data.noSearchResults": "Ingen søkeresultater",
    "data.statistics.header": "Statistikk",
    "data.statistics.loadingData": "Henter statistikken...",
    "data.statistics.totalRows": "Total antall:",
    "data.statistics.noStatisticsHeader": "Ingen statistikk tilgjengelig",
    "data.statistics.noStatisticsText": "Der kan dessverre ikke lages statistikk fra skjemedata",
    "data.statistics.loadingGraph": "Tegner graf...",
    "data.maxSubmissions": "Antall innsendelser",
    "data.maxSubmissions.header": "Begrens antall innsendelser",
    "data.maxSubmissions.text": "Hvis du vil begrense antall innsendelser for skjemaet, kan du angi maksimalt antall under her og legge inn en beskjed til brukerne vis antall overskrides.",
    "data.maxSubmissions.message.heading": "Overskrift",
    "data.maxSubmissions.message.body": "Tekst",
    "data.maxSubmissionsPerUser": "Flere innsendelser",
    "data.maxSubmissionsPerUser.header": "Flere innsendelser per bruker",
    "data.maxSubmissionsPerUser.text": "Hvis du ikke vil at samme bruker skal kunne sende inn skjemaet flere ganger kan du velge det her.",
    "data.disallowMultipleSubmissionsPerUser": "Kun én innsendelse per bruker",
    "data.maxSubmissionsPerUser.message.heading": "Overskrift",
    "data.maxSubmissionsPerUser.message.body": "Tekst",
    "data.daysBeforeExpiry": "Antall dager før sletting",
    "data.daysBeforeExpiry.helpText": "Skriv inn antall dager før innsendte data skal beholdes før det slettes automatisk. La feltet være tomt hvis det ikke skal slettes automatisk.",
  
    "edit.campaignMonitor.nameField": "Felt til navn",  
    "edit.campaignMonitor.nameField.helpText": "Hvilket felt inneholder navnet?",  
    "edit.checkbox.checked.helpText": "Sett kryss her hvis feltet skal være valgt som standard",  
    "edit.checked": "Valgt",  
    "edit.close": "Lukk",
    "edit.defaultText": "Standardvalg", 
    "edit.defaultText.helpText": "F.eks. \"Velg...\" - hvis denne er tom, vises ingen standardtekst", 
    "edit.edit": "Rediger",
    "edit.email.allowMultiple": "Tillat mer enn én",
    "edit.email.allowMultiple.helpText": "Sett kryss her hvis brukeren skal kunne legg inn mer enn en e-postadresse",
    "edit.errorMessage": "Feilmelding",
    "edit.errorMessage.helpText": "Meldingen som vises til brukeren vis ikke skjemaet er gyldig", 
    "edit.header.text.helpText": "Teksten som skal vises i overskriften",
    "edit.helpText": "Hjelpetekst",  
    "edit.helpText.helpText": "Forklarende tekst til brukeren", 
    "edit.image.choose": "Velg bilde",
    "edit.image.choose.helpText": "Klikk nedenfor for at velge et bilde",
    "edit.image.caption": "Bildetekst",
    "edit.image.caption.helpText": "Teksten som skal vises til bildet",
    "edit.label": "Etikett",  
    "edit.label.helpText": "Teksten som vises til brukeren", 
    "edit.link.text": "Tekst",
    "edit.link.text.helpText": "Teksten som skal vises som en link",
    "edit.link.target": "Mål",
    "edit.link.target.helpText": "Velg en side som skal linkes til",
    "edit.link.select": "Velg...",
    "edit.link.openInNewWindow": "Åpne i nytt vindu",
    "edit.link.openInNewWindow.helpText": "Sett kryss her hvis linken skal åpne i nytt vindu",
    "edit.mandatory": "Obligatorisk", 
    "edit.mandatory.helpText": "Sett kryss her hvis feltet er obligatorisk", 
    "edit.maxLength": "Maks antall tegn",
    "edit.maxLength.helpText": "Maks antall tegn i feltet (0 = uendelig)",
    "edit.memberInfo.helpText": "Når dette felt er fylt ut i skjemaet, blir navn og e-post automatisk lagret fra medlemmer som er logget inn",
    "edit.name": "Navn",  
    "edit.name.helpText": "Navnet må være unikt",
    "edit.number.minimum": "Minimum",
    "edit.number.minimum.helpText": "Det laveste tillatte tall",
    "edit.number.maximum": "Maximum",
    "edit.number.maximum.helpText": "Det høyeste tillatte tall",
    "edit.ok": "Lagre",
    "edit.options": "Valgmuligheter",
    "edit.options.add": "Legg til valgmulighet",  
    "edit.options.helpText": "Legg til valgmuligheter som brukeren skal kunne velge mellom",
    "edit.options.selected": "Valgt",  
    "edit.placeholder": "Plassholder/hjelpetekst",  
    "edit.placeholder.helpText": "Tekst som vises i feltet når det ikke er fylt ut", 
    "edit.renameWarning": "Hvis du gir nytt navn til felt vil du ikke lenger kunne se innsendt data", 
    "edit.selectbox.multiSelect": "Tillat flere valg",
    "edit.selectbox.multiSelect.helpText": "Sett kryss hvis brukeren skal kunne velge flere", 
    "edit.selectbox.size": "Antall viste valgmuligheter",
    "edit.selectbox.size.all": "Alle tilgjengelige valgmuligheter", 
    "edit.selectbox.size.helpText": "Der blir vist en scrollbar, hvis du velger et antall som er lavere enn tilgjengelige valg", 
    "edit.submitButton.label": "Knappens tekst",
    "edit.submitButton.label.helpText": "Teksten som vises på knappen - f.eks. \"Lagre\" eller \"Send inn\"",
    "edit.text": "Tekst",
    "edit.textParagraph.text.helpText": "Teksten der skal vises i avsnittet",
    "edit.upload.allowedFileTypes": "Tillatte filtyper",
    "edit.upload.allowedFileTypes.helpText": "F.eks. \"JPG, PNG, GIF\"",
    "edit.upload.maxSize": "Max fil-størrelse (KB)",
    "edit.upload.maxSize.helpText": "0 = ubegrenset",
  
    "common.clickToExpand": "klikk for mer"
}
